### PR TITLE
OTWO-5945 Removed secondbase gem and updated structure.sql

### PR DESCRIPTION
**Pull request by Priya5**

### CODE REVIEW

**Comment by karthikeyanBD** [comment]
I see the following sequences has not assigned to any schema.
```
openhub_development=# \d
                      List of relations
 Schema |           Name            |   Type   |    Owner
--------+---------------------------+----------+--------------
 public | analysis_sloc_sets_id_seq | sequence | openhub_user
 public | code_sets_id_seq          | sequence | openhub_user
 public | commits_id_seq            | sequence | openhub_user
 public | diffs_id_seq              | sequence | openhub_user
 public | forges_id_seq             | sequence | openhub_user
 public | fyles_id_seq              | sequence | openhub_user
 public | jobs_id_seq               | sequence | openhub_user
 public | pg_stat_statements        | view     | openhub_user
 public | repositories_id_seq       | sequence | openhub_user
 public | slave_logs_id_seq         | sequence | openhub_user
 public | slave_permissions_id_seq  | sequence | openhub_user
 public | sloc_metrics_id_seq       | sequence | openhub_user
 public | sloc_sets_id_seq          | sequence | openhub_user
(13 rows)
```

**Comment by karthikeyanBD** [comment]
We can remove foreign database related env values
```
FOREIGN_DB_HOST =
FOREIGN_DB_NAME =
FOREIGN_DB_USERNAME =
FOREIGN_DB_PASSWORD =
FOREIGN_DB_PORT =
```

**Comment by karthikeyanBD** [comment]
Can we remove `lib/tasks/fix_fdw_credentials.rake`?

**Comment by Priya5** [comment]
> Can we remove `lib/tasks/fix_fdw_credentials.rake`?

Yes, we can remove this task.

**Comment by Priya5** [comment]
> We can remove foreign database related env values
> 
> ```
> FOREIGN_DB_HOST =
> FOREIGN_DB_NAME =
> FOREIGN_DB_USERNAME =
> FOREIGN_DB_PASSWORD =
> FOREIGN_DB_PORT =
> ```

Sure, We will remove it.

**Pull request merged**
