### PR TITLE
OTWO-5690 Add health route for monitoring

### PR DESCRIPTION
**Pull request by notalex**

### CODE REVIEW

**Comment by PDegenPortnoy** [comment]
672 errors, 'ActiveRecord::NoDatabaseError: FATAL:  role "jenkins" does not exist'

**Comment by notalex** [comment]
The **/health** route would resolve if ActiveRecord has a connection to the DB. But there are other fail points. Like failure to connect to secondary database, database being out of space etc. We should list out the cases where the **/health** route should fail.

**Comment by PDegenPortnoy** [comment]
Good points @notalex. It looks like `/health` should fail when the Rails app cannot access primary or secondary DB (the DB Out of Space error will cause the DB service to stop), or when it cannot access Sidekiq or Redis.

Does that seem sufficient?

**Comment by notalex** [comment]
Yes. That is correct. We should be covered. This would return 500 in all failure cases.

**Pull request merged**
