### PR TITLE
Make git default SCM type for new enlistments

### PR DESCRIPTION
**Pull request by intgr**
Hey, 1990s called, they want their Subversion back :)

### CODE REVIEW

**Comment by intgr** [comment]
NB! Not tested at all, this just felt right.

**Comment by mattst88** [comment]
Yes, please.

**Comment by intgr** [comment]
Ping @rapbhan? This has been sitting forever. Rebased onto latest master.

**Comment by PDegenPortnoy** [comment]
PR #1515 is addressing this issue and requiring the specification of the branch; no longer assuming "master" is the default since the git community is shifting to using "main" as well.

**Comment by intgr** [comment]
@PDegenPortnoy "Open source" projects that behave like this are frustrating.

I spent some of my time on trying to understand the Ohloh code -- which was not trivial without prior Ruby/Rails experience -- to make an change that's an obvious improvement.

But from Ohloh side, nobody took the time to review or **or even reply** to my merge request (apart from another user who wants this feature).

If you are not interested in external contributions, please make that clear in your "CONTRIBUTING" file, see here for documentation: 
https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by PDegenPortnoy** [comment]
@intr Please accept my apologies for the lack of response and comment to your PR. We are a small team working to maintain a number of critical applications and services without our organization and frankly feel the same frustration you express in not being suitably responsive to members of the OSS community.  The Open Hub cannot function and won't exist without the participation and support of the community. I am grateful for your submission, apologize that I didn't give it the attention it deserved and will strive to do better in the future.

**Comment by intgr** [comment]
OK thanks :) I think I overreacted a bit too.

**Comment by PDegenPortnoy** [comment]
No worries. Thanks for expressing yourself.

**Pull request closed without merging**
