### PR TITLE
OTWO-4843 - Add additional failure group categories to capture uncate…

### PR DESCRIPTION
**Pull request by msk999**
…gorized failed jobs.

Created new script that creates new failure group records and categorizes failed jobs that were not originally categorized.
Final results - ability to categorize ~ 150k uncategorized jobs.  

Please review the new failure groups  - they are all set not to auto_reschedule.  Not sure if that is correct in all instances.  Let me know if you think any of the groups should be set to auot_reschedule.

### CODE REVIEW

**Comment by drubio1989** [comment]
LGTM

**Comment by msk999** [comment]
Jenkins test environment has been fixed.  Tests now are passing.

**Comment by Priya5** [comment]
retest this please

**Comment by msk999** [comment]
@Priya5  - Are you seeing an issue with this PR?

**Comment by Priya5** [comment]
@msk999 - No issue with the PR. I added comment  "retest this please" to re-trigger the jenkins build.

**Pull request merged**
