### PR TITLE
OTWO-4996 Migrate authentication to Clearance

### PR DESCRIPTION
**Pull request by notalex**

### CODE REVIEW

**Comment by PDegenPortnoy** [comment]
I ran the tests then the branch in development mode, having run the migration on the openhub_development.  I was able to sign in and navigate around the site as expected.  All seems to be working as expected.  We should deploy to staging and test further

**Comment by santhanakarthikeyan** [comment]
:+1:

**Comment by notalex** [comment]
retest this please

**Comment by PDegenPortnoy** [comment]
retest this please

**Comment by santhanakarthikeyan** [comment]
LGTM

**Pull request merged**
