### PR TITLE
OTWO-5039 Restore login with email

### PR DESCRIPTION
**Pull request by PDegenPortnoy**
With the migration to Clearance, we lost the ability to login with an
email address.  This restores that feature.

There was also a regression failure where a disabled account was being
redirected to the "authenticate new" path. This was due to the
"!current_user.access.disabled?" in the
ApplicationController#redirect_for_spammer_verification method.  When a
user is disabled, then they'll get caught by a later before_action
filter, so this check isn't needed here.

### CODE REVIEW

**Comment by rapbhan** [comment]
retest this please

**Comment by PDegenPortnoy** [comment]
@rapbhan I still get a test failure:

```
  1) Failure:
AccountsController::edit#test_0007_must logout spammer trying to edit or update [/Users/pdegenportnoy/src/ohloh-ui/test/controllers/accounts_controller_test.rb:221]:
Expected response to be a redirect to <http://test.host/accounts/login-1988/disabled> but was a redirect to <http://test.host/authentications/new>.
Expected "http://test.host/accounts/login-1988/disabled" to be === "http://test.host/authentications/new".
```

**Comment by PDegenPortnoy** [comment]
I am using the latest from the branch.  Just confirmed that I have your latest changes.

**Comment by rapbhan** [comment]
Yes, I did had the same test failed on my local and after a couple of iterations, merging the `master` branch seems to fix the issue and it's all clean now.

**Pull request merged**
