### PR TITLE
OTWO-4800: Remove unused routes projects controller routes

### PR DESCRIPTION
**Pull request by drubio1989**

### CODE REVIEW

**Comment by PDegenPortnoy** [comment]
@drubio1989,

I did some more research and see that we get about 10,000 requests per day for the similar_by_tags URL as a GET request from project show pages:

```
192.231.134.131 - - [12/Jun/2017:06:50:30 -0400] "GET /p/ubuntu/similar_by_tags HTTP/1.0" 200 353 "https://www.openhub.net/p/ubuntu" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.231.134.131 - - [12/Jun/2017:06:50:48 -0400] "GET /p/oscsta/similar_by_tags HTTP/1.0" 200 434 "https://www.openhub.net/p/oscsta" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.231.134.131 - - [12/Jun/2017:06:50:50 -0400] "GET /p/daltap/similar_by_tags HTTP/1.0" 200 31 "https://www.openhub.net/p/daltap" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.231.134.131 - - [12/Jun/2017:06:51:04 -0400] "GET /p/oscsta/similar_by_tags HTTP/1.0" 200 434 "https://www.openhub.net/p/oscsta" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.231.134.131 - - [12/Jun/2017:06:51:24 -0400] "GET /p/oscsta/similar_by_tags HTTP/1.0" 200 434 "https://www.openhub.net/p/oscsta" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
```

We may need to be more selective and reject only POST requests to this URL

**Comment by drubio1989** [comment]
I've elected to remove the /p/<project>/similar_by_tags page for the following reason. Here is an image of the url.

screen shot 2017-06-20 at 12 17 53 am

The image above is the only thing that is displayed. If you compare this image with the projects 'Quick Reference' panel you will see the same information displayed (Pictured below).

screen shot 2017-06-20 at 12 18 07 am

This is why I removed it.

**Comment by rapbhan** [comment]
It seems the similar tags are loaded via AJAX on the project quick reference(show) page. So we can't delete the partial and route. We can try accepting only if its a AJAX request.

**Comment by drubio1989** [comment]
Youre right Paddy, I saw the problem on localhost:3000. Will fix.

**Comment by drubio1989** [comment]
retest this please

**Comment by drubio1989** [comment]
retest this please

**Comment by drubio1989** [comment]
I added ajax only acceptance of similar_by_tags so that it will render on the projects page. I also blocked this url on nginx in order to avoid errbit reporting of the InvalidAuthenticityToken.

**Comment by rapbhan** [comment]
LGTM ....please do squash your commits into one

**Comment by drubio1989** [comment]
Thanks Paddy. Will do

**Pull request merged**
