### PR TITLE
OTWO-6407: Add DNF filter on enlistment page

### PR DESCRIPTION
**Pull request by karthikeyanBD**

### CODE REVIEW

**Comment by karthikeyanBD** [comment]
I just duplicated code and it not the way but I have time constraint so did in this fashion.

**Review by sig-krasnick — COMMENTED** [review]
LGTM - unfortunately, no tests.  Will need to fix repo testing environment.

**Comment by karthikeyanBD** [comment]
retest this please

**Comment by karthikeyanBD** [comment]
retest this please

**Comment by sig-krasnick** [comment]
retest this please

**Pull request closed without merging**
