### PR TITLE
OTWO-4803 Dont render template if edit show page request is not a ajax request

### PR DESCRIPTION
**Pull request by Priya5**

### CODE REVIEW

**Comment by rapbhan** [comment]
LGTM

**Comment by rapbhan** [comment]
@Priya5 Also please ensure we 'resolve' the error(s) in errbit :)

**Comment by Priya5** [comment]
Sure @rapbhan

**Comment by Priya5** [comment]
retest this please

**Comment by Priya5** [comment]
retest this please

**Pull request merged**
